# Generated by Django 5.0.7 on 2024-08-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='apponment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_year', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_mileage', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('Name2', models.CharField(max_length=100)),
                ('phone2', models.CharField(max_length=100)),
                ('email2', models.CharField(max_length=100)),
                ('message2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'apponment',
            },
        ),
    ]
