# Generated by Django 5.0.7 on 2024-08-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_apponment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apponment',
            old_name='phone2',
            new_name='number2',
        ),
    ]
